import React from "react";
import ScrollContainer from "react-indiana-drag-scroll";
import styled from "styled-components";
const DragScroll = () => {
	return (
		<div style={{ height: "100vh" }}>
			<ScrollContainer className="container">
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
				<p>dragscroll</p>
			</ScrollContainer>
		</div>
	);
};

export default DragScroll;

const ScrollBox = styled.div`
	width: max-content;
	height: 500px;
	background-color: red;
	.container {
		display: flex;
		width: fit-content;
		height: inherit;
	}
	p {
		width: 200px;
		background-color: blue;
	}
`;
